# encoding: utf-8
require_relative 'helper'
require_relative 'test_access_token'
require_relative 'test_channel_account'
require_relative 'test_customer'
require_relative 'test_customer_event'
require_relative 'test_synced_object'
require_relative 'test_deal'
require_relative 'test_sync_api'
require_relative 'test_job_status_api'
require_relative 'test_server'
# require_relative 'test_shared_access_token'
