docker:
  db:
    adapter: sqlite3
    database: /data/syncdb.sqlite3
    pool: 2
    timeout: 5000
  app:
    url: http://api.51convert.cn
    data: /data/sample1.csv

development:
  db:
    adapter: sqlite3
    database: dev.sqlite3
    pool: 2
    timeout: 5000
  app:
    url: http://api.51convert.cn
    data: testdata.csv

development_jruby:
  db:
    adapter: jdbcsqlite3
    database: dev.sqlite3
    pool: 2
    timeout: 5000
  app:
    url: http://api.51convert.cn

test:
  db:
    adapter: sqlite3
    database: test.sqlite3
    pool: 5
    timeout: 5000
  app:
    url: http://api.51convert.cn
