stages:
  - test

test:
  stage: test

  script:
    - bundle install
    - COVEARGE=1; bundle exec rake clean test
    - bundle exec rake build

  tags:
    - ruby

  artifacts:
    paths:
    - coverage
    - pkg

  only:
    - master
    - /^test.*$/
