# inherit_from:
#   - .rubocop_todo.yml

AllCops:
  Exclude:
    # this file is generated 
    - 'convertlabsdk.gemspec'
    - 'db/schema.rb'
    - 'Rakefile'

Style/Encoding:
  Enabled: true
  Exclude:

Style/TrailingWhitespace:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 30

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 32

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 115

Metrics/ParameterLists:
  Max: 6
