# inherit_from:
#   - .rubocop_todo.yml

AllCops:
  Exclude:
    # this file is generated 
    - '**/schema.rb'

Lint/HandleExceptions:
  Exclude:
    - 'test/helper.rb'

Style/ClassVars:
  Exclude:
    - 'test/test_*.rb'

Style/EmptyLines:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/Encoding:
  Enabled: true

Style/TrailingWhitespace:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 30

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 32

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 200
