development:
  adapter: sqlite3
  database: dev.sqlite3
  pool: 2
  timeout: 5000

docker:
  adapter: postgresql
  encoding: unicode
  host: postgres
  database: postgres
  username: postgres
  password: mysecretpassword
  pool: 2
  checkout_timeout: 30

docker_sqlite:
  adapter: sqlite3
  database: /data/syncdb.sqlite3
  pool: 2
  timeout: 5000
