development:
  db:
    adapter: sqlite3
    database: dev.sqlite3
    pool: 5
    timeout: 5000
  app:
    url: http://api.51convert.cn

test: &test
  db:
    adapter: sqlite3
    database: test.sqlite3
    pool: 5
    timeout: 5000
  app:
    url: http://api.51convert.cn
