version: '2'

services:
  resque:
    image: syncer:0.6.1
    ports:
      - "9292:9292"
    depends_on:
      - redis
      - postgres
    command: resque
    volumes:
      # /data is used by sqlite3 adapter only.
      - ../run/data:/data
      - ../run/config:/app/config
    environment:
      CLAB_APPID: ${CLAB_APPID}
      CLAB_SECRET: ${CLAB_SECRET}
      CLAB_URL: "http://api.51convert.cn"
      RAILS_ENV: "docker"
      REDIS_HOST: "redis:6379"

  redis:
    image: redis:3-alpine

  postgres:
    image: postgres:9.5
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "mysecretpassword"
    volumes:
      - ../run/pgdata:/var/lib/postgresql/data