# encoding: utf-8

# source 'https://rubygems.org'
# use alternative side because the official site could be partially 
# blocked by GFW inside China
source 'https://ruby.taobao.org'

gem 'convertlabsdk', '0.5.0'

platforms :ruby do
  gem 'sqlite3'
end

platforms :jruby do
  # gem 'jruby-openssl'
  gem 'activerecord-jdbcsqlite3-adapter'
  gem 'jdbc-sqlite3'
end
