# encoding: utf-8

# source 'https://rubygems.org'
# use alternative side because the official site could be partially 
# blocked by GFW inside China
source 'https://ruby.taobao.org'

gem 'convertlabsdk', '0.6.1'
gem 'retries'

# only 1 database is required. the gem here should correspond to database.yml configuration
gem 'pg'
gem 'sqlite3'

# convenience only. use the same rake version as the SDK itself to avoid typing bundle exec ...
gem 'rake', '~> 10.4.2'

group :resque do
  gem 'resque'
  gem 'resque-pool'
  gem 'resque-scheduler'
end
