# encoding: utf-8

# source 'https://rubygems.org'
# use alternative side because the official site could be partially 
# blocked by GFW inside China
source 'https://ruby.taobao.org'

gem 'convertlabsdk', path: '../..'
gem 'sqlite3'
gem 'byebug'
