# encoding: utf-8

HERE = File.dirname(__FILE__)
$LOAD_PATH.unshift HERE unless $LOAD_PATH.include?(HERE)

begin
  require 'resque/tasks'
  require 'resque-scheduler'
  require 'resque/scheduler/tasks'
  require 'resque/pool'
  require 'resque/pool/tasks'
rescue LoadError
  puts 'resque not available'
end

require 'active_record'
require 'syncer'

def db_config
  env = ENV['RAILS_ENV'] || 'development'
  YAML::load(File.open('config/database.yml'))[env]
end

namespace :resque do

  task :setup do
    ActiveRecord::Base.establish_connection(db_config)
  end

  task 'pool:setup' do
    ActiveRecord::Base.connection.disconnect!
    Resque::Pool.after_prefork do |job|
      ActiveRecord::Base.establish_connection(db_config)
    end
  end

  task :setup_schedule => :setup do
    Resque.schedule = YAML.load_file("#{HERE}/config/resque-scheduler.yml")
  end

  task :scheduler => :setup_schedule

  task :web do 
    exec 'rackup config.ru'
  end
end

namespace :db do
  desc 'Migrate the database'
  task :migrate do
    ActiveRecord::Base.establish_connection(db_config)
    ActiveRecord::Migrator.migrate('db/migrate/')
    puts 'Database migrated.'
  end
end
